### ISSUE TITLE
Sketch too big???

### ISSUE THREAD

**Issue by dmeylman** [moononournation/ATtinyWatch#1]
Arduino: 1.8.8 (Windows 10), Board: "Digispark (Default - 16.5mhz)"

C:\Program Files (x86)\Arduino\arduino-builder -dump-prefs -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\LENOVO USER\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\LENOVO USER\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\LENOVO USER\Documents\Arduino\libraries -fqbn=digistump:avr:digispark-tiny -ide-version=10808 -build-path C:\Users\LENOVO~1\AppData\Local\Temp\arduino_build_485511 -warnings=none -build-cache C:\Users\LENOVO~1\AppData\Local\Temp\arduino_cache_789238 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.micronucleus.path=C:\Users\LENOVO USER\AppData\Local\Arduino15\packages\digistump\tools\micronucleus\2.0a4 -prefs=runtime.tools.micronucleus-2.0a4.path=C:\Users\LENOVO USER\AppData\Local\Arduino15\packages\digistump\tools\micronucleus\2.0a4 -prefs=runtime.tools.avr-gcc.path=C:\Users\LENOVO USER\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5 -prefs=runtime.tools.avr-gcc-4.8.1-arduino5.path=C:\Users\LENOVO USER\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5 -verbose C:\Users\LENOVO USER\Documents\Arduino\libraries\ATtinyWatch-master\ATtinyWatch\ATtinyWatch.ino
C:\Program Files (x86)\Arduino\arduino-builder -compile -logger=machine -hardware C:\Program Files (x86)\Arduino\hardware -hardware C:\Users\LENOVO USER\AppData\Local\Arduino15\packages -tools C:\Program Files (x86)\Arduino\tools-builder -tools C:\Program Files (x86)\Arduino\hardware\tools\avr -tools C:\Users\LENOVO USER\AppData\Local\Arduino15\packages -built-in-libraries C:\Program Files (x86)\Arduino\libraries -libraries C:\Users\LENOVO USER\Documents\Arduino\libraries -fqbn=digistump:avr:digispark-tiny -ide-version=10808 -build-path C:\Users\LENOVO~1\AppData\Local\Temp\arduino_build_485511 -warnings=none -build-cache C:\Users\LENOVO~1\AppData\Local\Temp\arduino_cache_789238 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.micronucleus.path=C:\Users\LENOVO USER\AppData\Local\Arduino15\packages\digistump\tools\micronucleus\2.0a4 -prefs=runtime.tools.micronucleus-2.0a4.path=C:\Users\LENOVO USER\AppData\Local\Arduino15\packages\digistump\tools\micronucleus\2.0a4 -prefs=runtime.tools.avr-gcc.path=C:\Users\LENOVO USER\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5 -prefs=runtime.tools.avr-gcc-4.8.1-arduino5.path=C:\Users\LENOVO USER\AppData\Local\Arduino15\packages\arduino\tools\avr-gcc\4.8.1-arduino5 -verbose C:\Users\LENOVO USER\Documents\Arduino\libraries\ATtinyWatch-master\ATtinyWatch\ATtinyWatch.ino
Using board 'digispark-tiny' from platform in folder: C:\Users\LENOVO USER\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7
Using core 'tiny' from platform in folder: C:\Users\LENOVO USER\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7
Detecting libraries used...
"C:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino5/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -w -x c++ -E -CC -mmcu=attiny85 -DF_CPU=16500000L -DARDUINO=10808 -DARDUINO_AVR_DIGISPARK -DARDUINO_ARCH_AVR "-IC:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\digistump\\hardware\\avr\\1.6.7\\cores\\tiny" "-IC:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\digistump\\hardware\\avr\\1.6.7\\variants\\digispark" "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511\\sketch\\ATtinyWatch.ino.cpp" -o nul
"C:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino5/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -w -x c++ -E -CC -mmcu=attiny85 -DF_CPU=16500000L -DARDUINO=10808 -DARDUINO_AVR_DIGISPARK -DARDUINO_ARCH_AVR "-IC:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\digistump\\hardware\\avr\\1.6.7\\cores\\tiny" "-IC:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\digistump\\hardware\\avr\\1.6.7\\variants\\digispark" "-IC:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\digistump\\hardware\\avr\\1.6.7\\libraries\\TinyWireM" "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511\\sketch\\ATtinyWatch.ino.cpp" -o nul
"C:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino5/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -w -x c++ -E -CC -mmcu=attiny85 -DF_CPU=16500000L -DARDUINO=10808 -DARDUINO_AVR_DIGISPARK -DARDUINO_ARCH_AVR "-IC:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\digistump\\hardware\\avr\\1.6.7\\cores\\tiny" "-IC:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\digistump\\hardware\\avr\\1.6.7\\variants\\digispark" "-IC:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\digistump\\hardware\\avr\\1.6.7\\libraries\\TinyWireM" "-IC:\\Users\\LENOVO USER\\Documents\\Arduino\\libraries\\EEPROM-master" "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511\\sketch\\ATtinyWatch.ino.cpp" -o nul
"C:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino5/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -w -x c++ -E -CC -mmcu=attiny85 -DF_CPU=16500000L -DARDUINO=10808 -DARDUINO_AVR_DIGISPARK -DARDUINO_ARCH_AVR "-IC:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\digistump\\hardware\\avr\\1.6.7\\cores\\tiny" "-IC:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\digistump\\hardware\\avr\\1.6.7\\variants\\digispark" "-IC:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\digistump\\hardware\\avr\\1.6.7\\libraries\\TinyWireM" "-IC:\\Users\\LENOVO USER\\Documents\\Arduino\\libraries\\EEPROM-master" "-IC:\\Users\\LENOVO USER\\Documents\\Arduino\\libraries\\ATtinyWatch-master" "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511\\sketch\\ATtinyWatch.ino.cpp" -o nul
Using cached library dependencies for file: C:\Users\LENOVO USER\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\libraries\TinyWireM\TinyWireM.cpp
Using cached library dependencies for file: C:\Users\LENOVO USER\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\libraries\TinyWireM\USI_TWI_Master.cpp
Using cached library dependencies for file: C:\Users\LENOVO USER\Documents\Arduino\libraries\EEPROM-master\EEPROM.cpp
Using cached library dependencies for file: C:\Users\LENOVO USER\Documents\Arduino\libraries\ATtinyWatch-master\WDT_Time.cpp
Using cached library dependencies for file: C:\Users\LENOVO USER\Documents\Arduino\libraries\ATtinyWatch-master\ssd1306.cpp
Generating function prototypes...
"C:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino5/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -w -x c++ -E -CC -mmcu=attiny85 -DF_CPU=16500000L -DARDUINO=10808 -DARDUINO_AVR_DIGISPARK -DARDUINO_ARCH_AVR "-IC:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\digistump\\hardware\\avr\\1.6.7\\cores\\tiny" "-IC:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\digistump\\hardware\\avr\\1.6.7\\variants\\digispark" "-IC:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\digistump\\hardware\\avr\\1.6.7\\libraries\\TinyWireM" "-IC:\\Users\\LENOVO USER\\Documents\\Arduino\\libraries\\EEPROM-master" "-IC:\\Users\\LENOVO USER\\Documents\\Arduino\\libraries\\ATtinyWatch-master" "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511\\sketch\\ATtinyWatch.ino.cpp" -o "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511\\preproc\\ctags_target_for_gcc_minus_e.cpp"
"C:\\Program Files (x86)\\Arduino\\tools-builder\\ctags\\5.8-arduino11/ctags" -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511\\preproc\\ctags_target_for_gcc_minus_e.cpp"
Compiling sketch...
"C:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino5/bin/avr-g++" -c -g -Os -w -fno-exceptions -ffunction-sections -fdata-sections -MMD -mmcu=attiny85 -DF_CPU=16500000L -DARDUINO=10808 -DARDUINO_AVR_DIGISPARK -DARDUINO_ARCH_AVR "-IC:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\digistump\\hardware\\avr\\1.6.7\\cores\\tiny" "-IC:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\digistump\\hardware\\avr\\1.6.7\\variants\\digispark" "-IC:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\digistump\\hardware\\avr\\1.6.7\\libraries\\TinyWireM" "-IC:\\Users\\LENOVO USER\\Documents\\Arduino\\libraries\\EEPROM-master" "-IC:\\Users\\LENOVO USER\\Documents\\Arduino\\libraries\\ATtinyWatch-master" "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511\\sketch\\ATtinyWatch.ino.cpp" -o "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511\\sketch\\ATtinyWatch.ino.cpp.o"
Compiling libraries...
Compiling library "TinyWireM"
Using previously compiled file: C:\Users\LENOVO~1\AppData\Local\Temp\arduino_build_485511\libraries\TinyWireM\USI_TWI_Master.cpp.o
Using previously compiled file: C:\Users\LENOVO~1\AppData\Local\Temp\arduino_build_485511\libraries\TinyWireM\TinyWireM.cpp.o
Compiling library "EEPROM-master"
Using previously compiled file: C:\Users\LENOVO~1\AppData\Local\Temp\arduino_build_485511\libraries\EEPROM-master\EEPROM.cpp.o
Compiling library "ATtinyWatch-master"
Using previously compiled file: C:\Users\LENOVO~1\AppData\Local\Temp\arduino_build_485511\libraries\ATtinyWatch-master\WDT_Time.cpp.o
Using previously compiled file: C:\Users\LENOVO~1\AppData\Local\Temp\arduino_build_485511\libraries\ATtinyWatch-master\ssd1306.cpp.o
Compiling core...
Using previously compiled file: C:\Users\LENOVO~1\AppData\Local\Temp\arduino_build_485511\core\pins_arduino.c.o
Using precompiled core: C:\Users\LENOVO~1\AppData\Local\Temp\arduino_cache_789238\core\core_digistump_avr_digispark-tiny_2501827a70560e0226db8efb83e367e5.a
Linking everything together...
"C:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino5/bin/avr-gcc" -Os -Wl,--gc-sections -mmcu=attiny85 -o "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511/ATtinyWatch.ino.elf" "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511\\sketch\\ATtinyWatch.ino.cpp.o" "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511\\libraries\\TinyWireM\\TinyWireM.cpp.o" "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511\\libraries\\TinyWireM\\USI_TWI_Master.cpp.o" "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511\\libraries\\EEPROM-master\\EEPROM.cpp.o" "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511\\libraries\\ATtinyWatch-master\\WDT_Time.cpp.o" "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511\\libraries\\ATtinyWatch-master\\ssd1306.cpp.o" "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511\\core\\pins_arduino.c.o" "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_cache_789238\\core\\core_digistump_avr_digispark-tiny_2501827a70560e0226db8efb83e367e5.a" "-LC:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511" -lm
"C:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino5/bin/avr-objcopy" -O ihex -j .eeprom --set-section-flags=.eeprom=alloc,load --no-change-warnings --change-section-lma .eeprom=0 "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511/ATtinyWatch.ino.elf" "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511/ATtinyWatch.ino.eep"
"C:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino5/bin/avr-objcopy" -O ihex -R .eeprom "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511/ATtinyWatch.ino.elf" "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511/ATtinyWatch.ino.hex"
Using library TinyWireM at version 1.0.0 in folder: C:\Users\LENOVO USER\AppData\Local\Arduino15\packages\digistump\hardware\avr\1.6.7\libraries\TinyWireM 
Using library EEPROM-master at version 2.0 in folder: C:\Users\LENOVO USER\Documents\Arduino\libraries\EEPROM-master 
Using library ATtinyWatch-master in folder: C:\Users\LENOVO USER\Documents\Arduino\libraries\ATtinyWatch-master (legacy)
"C:\\Users\\LENOVO USER\\AppData\\Local\\Arduino15\\packages\\arduino\\tools\\avr-gcc\\4.8.1-arduino5/bin/avr-size" -A "C:\\Users\\LENOVO~1\\AppData\\Local\\Temp\\arduino_build_485511/ATtinyWatch.ino.elf"
Sketch uses 7388 bytes (122%) of program storage space. Maximum is 6012 bytes.

Global variables use 124 bytes of dynamic memory.
Sketch too big; see http://www.arduino.cc/en/Guide/Troubleshooting#size for tips on reducing it.
Error compiling for board Digispark (Default - 16.5mhz).

Please help. Thanks

**Comment by moononournation** [comment]
Please be noted that this is ATtinyWatch but not DigisparkWatch. 7388 bytes can fit in ATtiny85 8 KB flash memory, so it is not an issue. And also please be noted that running at 16.5mhz require calibration with USB port frequency while power up so you cannot make it as a watch.

**Comment by dmeylman** [comment]
Ok, thanks for the quick reply. I've ordered an attiny85. I'll try again. Thanks again...
